repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: insert-license
        files: \.py$
        args:
        - --license-filepath
        - license_header.txt
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [flake8-blind-except, flake8-builtins, flake8-bugbear, flake8-docstrings,
                                  flake8-import-order, flake8-mutable]
        files: ^automl_utils
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: [-l, '120']